version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: sh -c "yarn install && yarn run dev"
    image: bg-boiler-api
    ports:
      - 5200:5821
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./app:/app
    # environment:
    #   NODE_ENV: production

networks:
  backend-server:
    
